### ISSUE TITLE
DUDE

### ISSUE THREAD

**Issue by ArcheryAce** [IamnotTanzania/Stories#1]
Bruh there is no email

**Comment by KaasToast** [comment]
🥶

**Comment by ArcheryAce** [comment]
Dude we are fucking with ya there is no email

**Comment by IamnotTanzania** [comment]
bro screw that

**Comment by KaasToast** [comment]
https://user-images.githubusercontent.com/80634889/152675895-5fa3a05d-e373-4aa1-bc8a-19854dc4d21c.mp4
